Documentation:
  Enabled: false

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  DisplayCopNames: true
  SuggestExtensions: false
  Exclude:
    - config/puma.rb
    - 'db/**/*.rb'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'bin/bundle'
